arkemis/arke-postgres

.github/workflows/publish_hex.yml, mix.exs
chore: add links to package def
=> chore(CI): add release workflow

mix.exs
=> fix: umbrella deps

lib/mix/tasks/arke_postgres.init_db.ex
=> fix: init_db task waits for arke_auth

lib/mix/tasks/arke_postgres.init_db.ex
=> fix: add arke_auth to ensure load

lib/arke_postgres/query.ex
=> fix: date sorting

lib/arke_postgres/query.ex
=> fix: date, time and datetime query

lib/arke_postgres/query.ex
=> fix: with filters

lib/arke_postgres.ex, lib/mix/tasks/arke_postgres.create_project.ex, lib/mix/tasks/arke_postgres.init_db.ex
=> fix: env test

lib/arke_postgres/query.ex
add query to check for NULL values in db using the ISNULL statement
fixes [#12](https://github.com/arkemishub/arke-postgres/issues/12)
=> feat: isnull query

lib/mix/tasks/arke_postgres.create_project.ex, lib/mix/tasks/arke_postgres.init_db.ex
if the arke_postgres process is already started go on with the  task otherwise start it and then proceed
=> fix: mix task if process already started

lib/arke_postgres/query.ex
=> fix: adjust how link parameters are handled

lib/arke_postgres/query.ex
=> fix: adjust how int and floats are parsed

lib/arke_postgres/query.ex
=> fix: adjust postgres datetime cast

lib/arke_postgres/query.ex
wait for https://github.com/arkemishub/arke/pull/86 as the Utils is there
=> chore: use Arke utils for init

lib/arke_postgres/query.ex
add distinct select in both count and topology query
=> fix: topology query distinct

lib/arke_postgres/query.ex
=> feat: add distinct to query link by id and starting unit

lib/arke_postgres/query.ex
backport of PR:
- chore: https://github.com/arkemishub/arke-postgres/pull/35
- feat: https://github.com/arkemishub/arke-postgres/pull/38
=> fix: [backport] add starting_unit to link query

lib/arke_postgres/query.ex
=> fix: make handle_fiters public

lib/arke_postgres/query.ex
=> fix: default metadata init unit

lib/arke_postgres/query.ex
=> feat: add management for adding metadata in parameter and arke manager

lib/arke_postgres.ex
=> chore: print err

lib/arke_postgres/query.ex
Handle joined query if `path` is passed within query filters
=> feat: add nested filters and sort

.github/workflows/publish_hex.yml
=> fix: gh action
